name: rapids_spatial_viz
channels:
  - rapidsai
  - plotly
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - plotly=4.14
  - cudf
  - cuspatial
  - cugraph
  - dash
  - dask
  - dask-cuda
  - dask-cudf
  - cudatoolkit=11.0
  - dash-daq
  - dash-bootstrap-components
  - jupyter-dash
  - pyproj=2.6.1
  - pandas=1.1.3
  - geopandas
  - pyrosm
  - pip
  - pip:
    - dash-leaflet
    - dash-extensions
